# This is a basic workflow to help you gets started with Actions.

name: Deploy-Frontend

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #- uses: actions/checkout@v1

    #- name: Rebuild and deploy
     # run: |
     #   cd /opt/matcha/frontend/
     #   rm -rf app

    #- name: "Clone fresh copy"
    #  run: git clone https://github.com/rachel-e-bolton/Matcha-FrontEnd.git /opt/matcha/frontend/app
    - name: Pull latest
      run: |
        cd /opt/matcha/frontend/app
        git pull origin master
      
     
    - name: Running npm install
      run: |
        cd /opt/matcha/frontend/app
        /usr/local/bin/npm install --silent --production
        
    - name: Building application
      run: |
        cd /opt/matcha/frontend/app
        /usr/local/bin/npm run build
        
    - name: Changing ownership of application directory
      run: chown matcha:www-data /opt/matcha/frontend/ -R
